/**
 * Recursos de mídia e do realm Anfitrião: mecânicas, protótipos, resources, artworks, comics, filmes, faixas, vídeos, notas e tiras.
 * Parte da configuração de recursos do /admin — ver resource-types.ts para os
 * tipos/helpers e resources.ts para a montagem do mapa RESOURCES.
 */
import { z } from "zod"

import { CACHE_TAGS } from "@/lib/repos/tags"
import { type ResourceConfig, tagList, bool, int, optText } from "./resource-types"

export const MEDIA_RESOURCES: Record<string, ResourceConfig> = {
  mechanics: {
    slug: "mechanics",
    label: "Caderno (Mecânicas)",
    singular: "Mecânica",
    tag: CACHE_TAGS.mechanics,
    orderBy: { column: "sort", ascending: true },
    columns: [{ name: "title", label: "Mecânica" }],
    fields: [
      { name: "title", label: "Nome", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "summary", label: "Resumo", type: "textarea" },
      { name: "body", label: "Explicação (Markdown)", type: "markdown" },
      { name: "tags", label: "Tags", type: "tags" },
      { name: "published", label: "Publicado", type: "boolean" },
      { name: "sort", label: "Ordem", type: "number" },
    ],
    schema: z.object({
      title: z.string().min(1, "Nome obrigatório"),
      slug: z.string().min(1).regex(/^[a-z0-9-]+$/, "minúsculas, números e hífens"),
      summary: z.string().default(""),
      body: z.string().default(""),
      tags: tagList,
      published: bool,
      sort: int,
    }),
  },

  prototypes: {
    slug: "prototypes",
    label: "Laboratório (Protótipos)",
    singular: "Protótipo",
    tag: CACHE_TAGS.prototypes,
    orderBy: { column: "sort", ascending: true },
    columns: [
      { name: "title", label: "Título" },
      { name: "status", label: "Status" },
    ],
    fields: [
      { name: "title", label: "Título", type: "text", required: true },
      { name: "description", label: "Descrição", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: [
          { value: "conceito", label: "Conceito" },
          { value: "prototipo", label: "Protótipo" },
          { value: "playtest", label: "Playtest" },
          { value: "publicado", label: "Publicado" },
        ],
      },
      { name: "players", label: "Jogadores", type: "text", placeholder: "2–4" },
      { name: "playtime", label: "Duração", type: "text", placeholder: "45 min" },
      { name: "tags", label: "Tags", type: "tags" },
      { name: "published", label: "Publicado", type: "boolean" },
      { name: "sort", label: "Ordem", type: "number" },
    ],
    schema: z.object({
      title: z.string().min(1, "Título obrigatório"),
      description: z.string().default(""),
      status: z.enum(["conceito", "prototipo", "playtest", "publicado"]).default("conceito"),
      players: z.string().default(""),
      playtime: z.string().default(""),
      tags: tagList,
      published: bool,
      sort: int,
    }),
  },

  resources: {
    slug: "resources",
    label: "Imprensa (Recursos)",
    singular: "Recurso",
    tag: CACHE_TAGS.resources,
    orderBy: { column: "sort", ascending: true },
    columns: [
      { name: "title", label: "Título" },
      { name: "type", label: "Tipo" },
    ],
    fields: [
      { name: "title", label: "Título", type: "text", required: true },
      { name: "description", label: "Descrição", type: "textarea" },
      {
        name: "type",
        label: "Tipo",
        type: "select",
        options: [
          { value: "pnp", label: "Print & Play" },
          { value: "cartas", label: "Cartas" },
          { value: "tabuleiro", label: "Tabuleiro" },
          { value: "regras", label: "Regras" },
          { value: "outro", label: "Outro" },
        ],
      },
      { name: "file_url", label: "Arquivo (URL)", type: "media" },
      { name: "published", label: "Publicado", type: "boolean" },
      { name: "sort", label: "Ordem", type: "number" },
    ],
    schema: z.object({
      title: z.string().min(1, "Título obrigatório"),
      description: z.string().default(""),
      type: z.enum(["pnp", "cartas", "tabuleiro", "regras", "outro"]).default("pnp"),
      file_url: optText,
      published: bool,
      sort: int,
    }),
  },

  // ─── Zonas da landing /criativo ──────────────────────────────────────
  // Cada uma é uma "dimensão" da página pessoal: ateliê, banca, cine,
  // rádio, videoteca, mural e tirinhas.

  artworks: {
    slug: "artworks",
    label: "Ateliê (Artes)",
    singular: "Arte",
    tag: CACHE_TAGS.artworks,
    orderBy: { column: "sort", ascending: true },
    columns: [
      { name: "title", label: "Título" },
      { name: "kind", label: "Tipo" },
      { name: "year", label: "Ano" },
    ],
    fields: [
      { name: "title", label: "Título", type: "text", required: true },
      { name: "description", label: "Descrição", type: "textarea" },
      {
        name: "kind",
        label: "Tipo",
        type: "select",
        options: [
          { value: "ilustracao", label: "Ilustração" },
          { value: "edicao", label: "Edição de imagem" },
          { value: "3d", label: "3D" },
          { value: "pixel", label: "Pixel art" },
          { value: "vetor", label: "Vetor" },
          { value: "colagem", label: "Colagem" },
        ],
      },
      { name: "image", label: "Imagem", type: "media" },
      { name: "tools", label: "Ferramentas", type: "tags", help: "separadas por vírgula" },
      { name: "year", label: "Ano", type: "number" },
      { name: "published", label: "Publicado", type: "boolean" },
      { name: "sort", label: "Ordem", type: "number" },
    ],
    schema: z.object({
      title: z.string().min(1, "Título obrigatório"),
      description: z.string().default(""),
      kind: z.enum(["ilustracao", "edicao", "3d", "pixel", "vetor", "colagem"]).default("ilustracao"),
      image: z.string().default(""),
      tools: tagList,
      year: int,
      published: bool,
      sort: int,
    }),
  },

  comics: {
    slug: "comics",
    label: "Banca (Quadrinhos)",
    singular: "Quadrinho",
    tag: CACHE_TAGS.comics,
    orderBy: { column: "sort", ascending: true },
    columns: [
      { name: "title", label: "Título" },
      { name: "author", label: "Autor" },
      { name: "status", label: "Status" },
    ],
    fields: [
      { name: "title", label: "Título", type: "text", required: true },
      { name: "author", label: "Autor", type: "text" },
      { name: "publisher", label: "Editora", type: "text" },
      { name: "cover_image", label: "Capa", type: "media" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: [
          { value: "lendo", label: "Lendo agora" },
          { value: "lido", label: "Lido" },
          { value: "fila", label: "Na fila" },
          { value: "largado", label: "Larguei" },
        ],
      },
      { name: "rating", label: "Nota (0–5)", type: "number", help: "0 = sem nota" },
      { name: "note", label: "Comentário", type: "textarea" },
      { name: "published", label: "Publicado", type: "boolean" },
      { name: "sort", label: "Ordem", type: "number" },
    ],
    schema: z.object({
      title: z.string().min(1, "Título obrigatório"),
      author: z.string().default(""),
      publisher: z.string().default(""),
      cover_image: z.string().default(""),
      status: z.enum(["lendo", "lido", "fila", "largado"]).default("lendo"),
      rating: z.preprocess((v) => (v === "" || v == null ? 0 : Number(v)), z.number().int().min(0).max(5)),
      note: z.string().default(""),
      published: bool,
      sort: int,
    }),
  },

  movies: {
    slug: "movies",
    label: "Cine (Filmes)",
    singular: "Filme",
    tag: CACHE_TAGS.movies,
    orderBy: { column: "sort", ascending: true },
    columns: [
      { name: "title", label: "Título" },
      { name: "director", label: "Direção" },
      { name: "status", label: "Status" },
    ],
    fields: [
      { name: "title", label: "Título", type: "text", required: true },
      { name: "director", label: "Direção", type: "text" },
      { name: "year", label: "Ano", type: "number" },
      { name: "poster_image", label: "Pôster", type: "media" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: [
          { value: "assistido", label: "Assistido" },
          { value: "assistindo", label: "Assistindo" },
          { value: "fila", label: "Na fila" },
        ],
      },
      { name: "rating", label: "Nota (0–5)", type: "number", help: "0 = sem nota" },
      { name: "note", label: "Comentário", type: "textarea" },
      { name: "published", label: "Publicado", type: "boolean" },
      { name: "sort", label: "Ordem", type: "number" },
    ],
    schema: z.object({
      title: z.string().min(1, "Título obrigatório"),
      director: z.string().default(""),
      year: int,
      poster_image: z.string().default(""),
      status: z.enum(["assistido", "assistindo", "fila"]).default("assistido"),
      rating: z.preprocess((v) => (v === "" || v == null ? 0 : Number(v)), z.number().int().min(0).max(5)),
      note: z.string().default(""),
      published: bool,
      sort: int,
    }),
  },

  tracks: {
    slug: "tracks",
    label: "Rádio (Música)",
    singular: "Faixa",
    tag: CACHE_TAGS.tracks,
    orderBy: { column: "sort", ascending: true },
    columns: [
      { name: "title", label: "Título" },
      { name: "artist", label: "Artista" },
    ],
    fields: [
      { name: "title", label: "Título", type: "text", required: true },
      { name: "artist", label: "Artista", type: "text" },
      { name: "audio_url", label: "Áudio (mp3/ogg)", type: "media", help: "o player é local, não embed" },
      { name: "cover_image", label: "Capa", type: "media" },
      { name: "note", label: "Comentário", type: "textarea" },
      { name: "published", label: "Publicado", type: "boolean" },
      { name: "sort", label: "Ordem", type: "number" },
    ],
    schema: z.object({
      title: z.string().min(1, "Título obrigatório"),
      artist: z.string().default(""),
      audio_url: z.string().default(""),
      cover_image: z.string().default(""),
      note: z.string().default(""),
      published: bool,
      sort: int,
    }),
  },

  videos: {
    slug: "videos",
    label: "Videoteca",
    singular: "Vídeo",
    tag: CACHE_TAGS.videos,
    orderBy: { column: "sort", ascending: true },
    columns: [
      { name: "title", label: "Título" },
      { name: "kind", label: "Origem" },
    ],
    fields: [
      { name: "title", label: "Título", type: "text", required: true },
      { name: "description", label: "Descrição", type: "textarea" },
      { name: "video_url", label: "Vídeo (arquivo ou URL)", type: "media" },
      { name: "poster_image", label: "Pôster", type: "media" },
      {
        name: "kind",
        label: "Origem",
        type: "select",
        options: [
          { value: "local", label: "Arquivo local" },
          { value: "youtube", label: "YouTube" },
          { value: "vimeo", label: "Vimeo" },
        ],
      },
      { name: "published", label: "Publicado", type: "boolean" },
      { name: "sort", label: "Ordem", type: "number" },
    ],
    schema: z.object({
      title: z.string().min(1, "Título obrigatório"),
      description: z.string().default(""),
      video_url: z.string().default(""),
      poster_image: z.string().default(""),
      kind: z.enum(["local", "youtube", "vimeo"]).default("local"),
      published: bool,
      sort: int,
    }),
  },

  notes: {
    slug: "notes",
    label: "Mural (Recados)",
    singular: "Recado",
    tag: CACHE_TAGS.notes,
    orderBy: { column: "sort", ascending: true },
    columns: [
      { name: "title", label: "Título" },
      { name: "author", label: "Autor" },
      { name: "pinned", label: "Fixado" },
    ],
    fields: [
      { name: "title", label: "Título", type: "text" },
      { name: "body", label: "Recado", type: "textarea", required: true },
      { name: "author", label: "Autor", type: "text" },
      {
        name: "accent",
        label: "Cor do papel",
        type: "select",
        options: [
          { value: "yellow", label: "Amarelo" },
          { value: "cyan", label: "Ciano" },
          { value: "magenta", label: "Magenta" },
          { value: "lime", label: "Lima" },
          { value: "orange", label: "Laranja" },
          { value: "violet", label: "Violeta" },
        ],
      },
      { name: "pinned", label: "Fixado no topo", type: "boolean" },
      { name: "published", label: "Publicado", type: "boolean" },
      { name: "sort", label: "Ordem", type: "number" },
    ],
    schema: z.object({
      title: z.string().default(""),
      body: z.string().min(1, "Recado obrigatório"),
      author: z.string().default("Lucas"),
      accent: z.enum(["yellow", "cyan", "magenta", "lime", "orange", "violet"]).default("yellow"),
      pinned: bool,
      published: bool,
      sort: int,
    }),
  },

  strips: {
    slug: "strips",
    label: "Tirinhas",
    singular: "Tirinha",
    tag: CACHE_TAGS.strips,
    orderBy: { column: "sort", ascending: true },
    columns: [
      { name: "title", label: "Título" },
      { name: "setup", label: "Setup" },
    ],
    fields: [
      { name: "title", label: "Título", type: "text", required: true },
      { name: "image", label: "Imagem da tira", type: "media", help: "opcional — sem imagem, vira tira de texto" },
      { name: "setup", label: "Quadro 1 (setup)", type: "textarea" },
      { name: "punchline", label: "Quadro 2 (punchline)", type: "textarea" },
      { name: "published", label: "Publicado", type: "boolean" },
      { name: "sort", label: "Ordem", type: "number" },
    ],
    schema: z.object({
      title: z.string().min(1, "Título obrigatório"),
      image: z.string().default(""),
      setup: z.string().default(""),
      punchline: z.string().default(""),
      published: bool,
      sort: int,
    }),
  },
}
